In [ ]:
function LDLt(A)
    # Given an SPD matrix A_{n, n}
    # Output L and D
    n, n1 = size(A)
    v = zeros(n,1)
    L = eye(n)
    d = zeros(n,1)
    for i = 1:n
        # step 2
        for j = 1:i-1
            v[j] = L[i,j] * d[j]
        end
        
        # step 3
        temp = 0
        for j = 1:i-1
            temp = temp + L[i,j] * v[j]
        end
        d[i] = A[i,i] - temp
        
        #step 4
        for j = i+1:n
            temp = 0
            for k = 1:i-1
                temp = temp + L[j,k] * v[k]
            end
            L[j,i] = (A[j,i] - temp) / d[i]
        end
    end
    return L, d
end

In [ ]:
function tridiagLU(A)
    n, n1 = size(A)
    L = zeros(n,n)
    U = eye(n)
    L[1,1] = A[1,1]
    U[1,2] = A[1,2] / L[1,1]
    for i = 2:n-1
        L[i, i-1] = A[i,i-1]
        L[i,i] = A[i,i] - L[i,i-1] * U[i-1,i]
        U[i,i+1] = A[i,i+1] / L[i,i]
    end
    L[n,n-1] = A[n,n-1]
    L[n,n] =  A[n,n] - L[n,n-1]* U[n-1,n]
    return L, U
end

In [ ]:
function jacobi(A,b, x0, TOL, Nmax)
    n, n1 = size(A)
    x = zeros(n,1)
    for k = 1:Nmax
        for i = 1:n
            temp1 = 0
            for j = 1:i-1
                temp1 = temp1 + A[i,j] * x0[j]
            end
            
            temp2 = 0
            for j = i+1:n
                temp2 = temp2 + A[i,j] * x0[j]
            end
            
            x[i] = (-temp1 - temp2 + b[i]) /  A[i,i]
        end
        res = norm(x - x0, Inf)
        #println(k, '\t', res)
        if res < TOL
            return x
        end
        x0[1:n] = x[1:n]
    end
    println("Reached the maximum iterations! Solution might be wrong")
end

In [ ]:
function GS(A, b, x0, TOL, Nmax)
    n, n1 = size(A)
    x = zeros(n,1)
    for k = 1:Nmax
        for i = 1:n
            temp1 = 0
            for j = 1:i-1
                temp1 = temp1 + A[i,j] * x[j]
            end
            
            temp2 = 0
            for j = i+1:n
                temp2 = temp2 + A[i,j] * x0[j]
            end
            
            x[i] = ((-temp1) - temp2 + b[i]) /  A[i,i]
        end
        res = norm(x - x0, Inf) # make sure calculating inf norm
        #println(k, '\t', res)
        if res < TOL
            return x
        end
        x0[1:n] = x[1:n]
    end
    println("Reach the maximum iterations! Solution might be wrong")
end

# 7.3.9.

The linear system

$$2x_1 - x_2 + x_3 = -1$$
$$2x_1 + 2x_2 + 2x_3 = 4$$
$$-x_1 -x_2 + 2x_3 = -5$$

has the solution $(1,2,-1)^t$.

# b. 
Show that the Jacobi method with $x^{(0)} = 0$ fails to give a good approximation after 25 iterations.

In [19]:
A = [
    2 -1 1;
    2 2 2;
    -1 -1 2
]
b = [-1; 4; -5]
x0 = zeros(3,1)
TOL = 0.01
Nmax = 25
jacobi(A, b, x0, TOL, Nmax)

Reached the maximum iterations! Solution might be wrong


So we can see from the above output

> `Reached the maximum iterations! Solution might be wrong`

That the Jacobi method does not give a good approximation after 25 iterations.

# d.
Use the Gauss-Seidel method with $x(0) = 0$ to approximate the solution to the linear system to within $10^{−5}$ in the $l_∞$ norm.

In [20]:
# 7.3.9d
A = [
    2 -1 1;
    2 2 2;
    -1 -1 2
]
b = [-1; 4; -5]
x0 = zeros(3,1)
TOL = 1e-5
Nmax = 100
GS(A, b, x0, TOL, Nmax)

3x1 Array{Float64,2}:
  1.0
  2.0
 -1.0

# 7.3.15.

Use (a) the Jacobi and (b) the Gauss-Seidel methods to solve the linear system $Ax = b$ to within $10^{−5}$ in the $l_∞$ norm, where the entries of $A$ are

$$.$$
$$.$$
$$.$$


and those of $b$ are $b_i = π$, for each $i = 1,2,...,80$.

In [21]:
A_15 = zeros(80,80)
for i = 1:80
    A_15[i,i] = 2*i
    if i + 2 <= 80
        A_15[i, i+2] = 0.5*i
    end
    if i - 2 >= 1
        A_15[i, i-2] = 0.5*i
    end
    if i + 4 <= 80
        A_15[i, i+4] = 0.25*i
    end
    if i - 4 >= 1
        A_15[i, i-4] = 0.25*i
    end
end
b_15 = zeros(80,1)
for i = 1:80
    b_15[i] = pi
end

# a.

Jacobi method

In [22]:
TOL = 1e-5
Nmax = 100
x0 = zeros(80,1)
jacobi(A_15, b_15, x0, TOL, Nmax)

80x1 Array{Float64,2}:
 1.53874  
 0.731422 
 0.107971 
 0.173285 
 0.0405586
 0.0852502
 0.16645  
 0.121982 
 0.101253 
 0.0904597
 0.0720317
 0.070266 
 0.0687583
 ⋮        
 0.0129717
 0.0127866
 0.0127033
 0.0125272
 0.012377 
 0.0122101
 0.0112904
 0.0111414
 0.0121734
 0.0120177
 0.0154291
 0.0152381

# b.

Gauss-Seidel

In [23]:
# 7.3.15 Gauss-Seidel
TOL = 1e-5
Nmax = 100
x0 = zeros(80,1)
GS(A_15, b_15, x0, TOL, Nmax)

80x1 Array{Float64,2}:
 1.53873  
 0.73142  
 0.107969 
 0.173283 
 0.0405559
 0.0852479
 0.166447 
 0.121979 
 0.101249 
 0.0904566
 0.0720279
 0.0702627
 0.0687542
 ⋮        
 0.0129711
 0.012786 
 0.0127026
 0.0125266
 0.0123766
 0.0122097
 0.0112901
 0.011141 
 0.0121731
 0.0120175
 0.015429 
 0.015238 

# 16.

Suppose that an object can be at any one of n + 1 equally spaced points $x_0, x_1, . . . , x_n$. When an object is at location xi, it is equally likely to move to either $x_{i−1}$ or $x_{i+1}$ and cannot directly move to any other location. Consider the probabilities $\{P_i\}^{n}_{i=0}$ that an object starting at location xi will reach the left endpoint x0 before reaching the right endpoint xn. Clearly, $P_0 = 1$ and $P_n = 0$. Since the object can move to xi only from $x_{i−1}$ or $x_{i+1}$ and does so with probability $\frac{1}{2}$ for each of these locations,

$$
P_i = \frac{1}{2}P_{i-1} + \frac{1}{2}P_{i+1},
$$

for each $i = 1,2,...,n-1$.

# b.

Solve this system using $n = 10, 50,$ and $100$.

In [24]:
# 7.3.16b
n = 100
A = eye(n)
for i = 1:n
    if i != 1
        A[i,i-1] = -1/2
    end
    if i != n
        A[i, i+1] = -1/2
    end
end
A

b = zeros(n,1)
b[1] = 1/2

0.5

## Gauss-Sidel

In [25]:
x0 = zeros(n,1)
TOL = 1e-8
Nmax = 20000
GS(A, b, x0, TOL, Nmax)

100x1 Array{Float64,2}:
 0.990099  
 0.980197  
 0.970296  
 0.960395  
 0.950493  
 0.940592  
 0.930691  
 0.920789  
 0.910888  
 0.900987  
 0.891086  
 0.881184  
 0.871283  
 ⋮         
 0.118808  
 0.108907  
 0.0990068 
 0.0891061 
 0.0792054 
 0.0693047 
 0.0594041 
 0.0495034 
 0.0396027 
 0.029702  
 0.0198014 
 0.00990068

## Tridiagonal LU Solver

In [26]:
L, U = tridiagLU([A b])
y = L\b
x = U\y
x

100x1 Array{Float64,2}:
 0.990099  
 0.980198  
 0.970297  
 0.960396  
 0.950495  
 0.940594  
 0.930693  
 0.920792  
 0.910891  
 0.90099   
 0.891089  
 0.881188  
 0.871287  
 ⋮         
 0.118812  
 0.108911  
 0.0990099 
 0.0891089 
 0.0792079 
 0.0693069 
 0.0594059 
 0.049505  
 0.039604  
 0.029703  
 0.019802  
 0.00990099

## LDL Decomposition Solver

In [27]:
L, d = LDLt([A b])
D = zeros(n,n)
for i = 1:n
    D[i,i] = d[i]
end
y = L\b
z = D\y
x = transpose(L)\z
x

100x1 Array{Float64,2}:
 0.990099  
 0.980198  
 0.970297  
 0.960396  
 0.950495  
 0.940594  
 0.930693  
 0.920792  
 0.910891  
 0.90099   
 0.891089  
 0.881188  
 0.871287  
 ⋮         
 0.118812  
 0.108911  
 0.0990099 
 0.0891089 
 0.0792079 
 0.0693069 
 0.0594059 
 0.049505  
 0.039604  
 0.029703  
 0.019802  
 0.00990099