#Guassian Elimination and LU Decomposition

We consider no pivoting and no swapping case.  We need to solve the system of linear equations $$Ax = b,$$ where the dimension of $A$ is $n\times n$.  In general, the GE can be described as
* Do i = 1, ..., n
  * Do j = i+1, ..., n
    * $m_{ji} = \frac{a_{ji}}{a_{ii}}$
    * $R_j = -m_{ji}R_i + R_j$
* (Above completes the GE process. Below performs backward subsitution to obtain $x$.)
* $x_n = \frac{a_{n,n+1}}{a_{n,n}}$
* Do i = n-1, ..., 1
  * $x_i = [a_{i, n+1} - \sum_{j=i+1}^{n} a_{i,j} x_j] \big/ a_{i,i}$

In [1]:
function GE(A)
    #Given an augmented matrix A_{n, n+1}
    #Output the solution x to Ax = b.
    n, n1 = size(A)
    for i = 1:n
        for j = i + 1:n
            m = A[j,i]/A[i,i]
            A[j,:] = -m*A[i,:] + A[j,:]
        end
    end
    x = BackSub(A)
    return x
end

GE (generic function with 1 method)

In [11]:
function BackSub(U)  
    n, n1 = size(U)
    x = zeros(n, 1)
    x[n] = U[n,n+1]/U[n,n]
    for i = n-1:-1:1
        temp = 0 # to calculate the summation
        for j = i+1:n
            temp = temp + U[i,j] * x[j]
        end
        x[i] = (U[i,n+1] - temp) / U[i,i]
    end
    return x
end


BackSub (generic function with 1 method)

To test our code, we consider the example in the textbook on page 358.
$$
\begin{cases}
 &x_1 + x_2 + 3x_4 &= 4,\\
 &2x_1 + x_2 - x_3 + x_4 &= 1,\\
 &3x_1 - x_2 - x_3 + 2x_4 &= -3,\\
 &-x_1 + 2x_2 + 3x_3 - x_4 &=4
\end{cases}
,
$$
where the exact solution is $x = (-1, 2, 0, 1)$.

The augmented matrix is
$$
\begin{pmatrix}
 1 & 1 & 0 & 3 & 4 \\
 2 & 1 & -1& 1 & 1 \\
 3 & -1& -1& 2 & -3\\
 -1& 2 & 3 & -1& 4
\end{pmatrix}.
$$

In [3]:
A = [ 
    1 1 0 3 4;
    2 1 -1 1 1;
    3 -1 -1 2 -3;
    -1 2 3 -1 4
]

4x5 Array{Int64,2}:
  1   1   0   3   4
  2   1  -1   1   1
  3  -1  -1   2  -3
 -1   2   3  -1   4

In [4]:
GE(A)

4x1 Array{Float64,2}:
 -1.0
  2.0
  0.0
  1.0

##LU Decomposition
A = LU, where $L_{j,i} = m_{j,i}$ and $U$ is the matrix after GE.

###In Class Exercise.
Implement LU decomposition by modifying the Gaussian Elimination function ```GE```.  Run your code on the matrix $$
B =\begin{pmatrix}
 1 & 1 & 0 & 3  \\
 2 & 1 & -1& 1  \\
 3 & -1& -1& 2 \\
 -1& 2 & 3 & -1
\end{pmatrix},
$$
where the exact $L$ and $U$ are
$$
L = \begin{pmatrix}
 1 & 0 & 0 & 0  \\
 2 & 1 & 0 & 0  \\
 3 & 4& 1& 0 \\
 -1& -3 & 0 & 1
\end{pmatrix},\quad
U=
\begin{pmatrix}
 1 & 1 & 0 & 3  \\
 0 & -1 & -1& -5  \\
 0 & 0& 3& 13 \\
 0 & 0 & 0 & -13
\end{pmatrix}.
$$

In [5]:
function LUdecomp(A)
    n, n1 = size(A)
    L = eye(n)
    U = zeros(n,n1)
    for i = 1:n
        for j = i + 1:n
            m = A[j,i] / A[i,i]
            L[j,i] = m
            A[j,:] = -m*A[i,:] + A[j,:]

        end
    end
    U = A
    return L, U
end

LUdecomp (generic function with 1 method)

In [6]:
B = [ 1 1 0 3 ; 2 1 -1 1 ; 3 -1 -1 2 ; -1 2 3 -1]
LUdecomp(B)

(
4x4 Array{Float64,2}:
  1.0   0.0  0.0  0.0
  2.0   1.0  0.0  0.0
  3.0   4.0  1.0  0.0
 -1.0  -3.0  0.0  1.0,

4x4 Array{Int64,2}:
 1   1   0    3
 0  -1  -1   -5
 0   0   3   13
 0   0   0  -13)

##Determinant of a Matrix
Sinc the definition of the determinant is defined recursively (see Def 6.15 in the textbook), it is hard and inefficient to compute it by the definition.  One way to compute it is by the factorization method.  For example, because $A = LU$, $$\det(A) = \det(LU) = \det(L) \det(U).$$ Moreover, we know that $\det(L) = 1$ (why?); therefore, $$\det(A) = \det(U) = \Pi_{i=1}^{n} u_{i,i}.$$

Find the determinant of the matrix $B$.

In [9]:
L,U = LUdecomp(B)
n,n1 = size(B)
detB = 1
for i = 1:n
    detB = detB * U[i]
end

#Homework(Check the complete problem set on BB)
1. Modify the code ```GE``` so that it can deal with row interchanges (see Step 2 and 3 in Algorithm 6.1 on page 364).
2. Implement the forward substitution. 
3. Modify ```LUdecomp``` so that it can be used to solve a linear syste.

In [47]:
function mGE(A) # modified GE, handle swaps when neccessary
    # Given an augmented matrix A_{n, n+1}
    # Output the solution x to Ax = b.
    n, n1 = size(A)
    for i = 1:n
        if A[i,i] == 0 # swap
            found = false
            for k = i+1:n
                if A[k, i] != 0
                    A[i,:], A[k,:] = A[k,:], A[i,:]
                    found = true
                    break
                end
            end
            if !found
                return "no unique solution exists"
            end
        end
        for j = i+1:n
            m = A[j,i] / A[i,i]
            A[j,:] = -m*A[i,:] + A[j,:]
        end
    end
    x = BackSub(A)
    return x
end

m = [0 0 2 3; 1 1 4 5; 0 4 5 7]

println(mGE(m))

println([0 0 2; 1 1 4; 0 4 5 ]\[3;5;7])

[-0.875
 -0.125
 1.5]
[-0.875,-0.125,1.5]


In [50]:
function ForwardSub(L)  
    n, n1 = size(L)
    x = zeros(n, 1)
    x[1] = L[1,n+1] / U[1,1]
    for i = 2:n
        temp = 0
        for j = i-1:-1:1
            temp += L[i,j] * x[j]
        end
        x[i] = (L[i, n+1] - temp) / L[i,i]
    end
    return x
end

m = [1 0 0 1; 2 1 0 1; 3 4 1 1];
println(ForwardSub(m))
println([1 0 0; 2 1 0; 3 4 1]\[1;1;1])

[1.0
 -1.0
 2.0]
[1.0,-1.0,2.0]


In [57]:
function LUSolver(A,b)
    L, U = LUdecomp(A)
    y = ForwardSub([L b])
    x = BackSub([U y])
    return x
end
print(LUSolver([1 0 0; 2 1 0; 3 4 1], [1;1;1]))
println([1 0 0; 2 1 0; 3 4 1]\[1;1;1])

[1.0
 -1.0
 2.0][1.0,-1.0,2.0]


In [76]:
# 6.1 5a
A = [
    1 -1 3;
    3 -3 1;
    1  1 0;
]
b = [2; -1; 3]
println(mGE([A b]))
println(A\b)

[1.1875
 1.8125
 0.875]
[1.1875,1.8125,0.8750000000000001]


In [71]:
#6.1 5b
A = [
    2 -1.5 3;
    -1 0 2;
    4 -4.5 5
]
b = [1; 3; 1]
println(mGE([A b]))
println(A\b)

[-1.0
 -0.0
 1.0][-1.0,-0.0,1.0]

In [72]:
#6.1 5d
A = [
    1 1 0 4;
    2 1 -1 1;
    4 -1 -2 2;
    3 -1 -1 2
]
b = [2; 1; 0; -3]
println(mGE([A b]))
println(A\b)

[-4.000000000000001
 0.6666666666666679
 -7.0
 1.3333333333333333][-4.000000000000001,0.6666666666666679,-7.0,1.3333333333333333]

In [74]:
#6.5 8a
A = [
    1 -1 0;
    2 2  3;
    -1 3 2
]
b = [2; -1; 4]
println(mGE([A b]))
println(A\b)

3-element Array{Float64,1}:
 -12.0
 -14.0
  17.0

In [77]:
#6.5 8b
A = [
    1/3 1/2 -1/4;
    1/5 2/3 3/8;
    2/5 -2/3 5/8
]
b = [1; 2; -3]
println(mGE([A b]))
println(A\b)

[-2.0539419087136936
 3.485477178423237
 0.23236514522821583]
[-2.0539419087136923,3.4854771784232366,0.23236514522821505]
